import '../styles/header.scss';

export default $(()=> {
	let header = [
		'<div class="header">',
		'	<div class="top-bar">',
		'		<div class="navs">',
		'			<div class="nav popup">',
		'				<a href="#" class="title">网站导航<img class="search" src="/images/web/index/top-bar-arrow.png"></a>',
		'				<div class="popup-wrapper">',
		'					<div class="content">',
		'						<p><a href="#">正在建设中...</a></p>',
		'						<p><a href="#">正在建设中...</a></p>',
		'						<p><a href="#">正在建设中...</a></p>',
		'					</div>',
		'				</div>',
		'			</div>',
		'			<div class="nav popup">',
		'				<a href="#" class="title">全部课程<img class="search" src="/images/web/index/top-bar-arrow.png"></a>',
		'				<div class="popup-wrapper">',
		'					<div class="content">',
		'						<p><a href="#">正在建设中...</a></p>',
		'						<p><a href="#">正在建设中...</a></p>',
		'						<p><a href="#">正在建设中...</a></p>',
		'					</div>',
		'				</div>',
		'			</div>',
		'			<div class="nav popup">',
		'				<a href="#" class="title">考研工具<img class="search" src="/images/web/index/top-bar-arrow.png"></a>',
		'				<div class="popup-wrapper">',
		'					<div class="content">',
		'						<p><a href="#">正在建设中...</a></p>',
		'						<p><a href="#">正在建设中...</a></p>',
		'						<p><a href="#">正在建设中...</a></p>',
		'					</div>',
		'				</div>',
		'			</div>',
		'		</div>',
		'		<div class="icons">',
		'			<a href="app.html"><img class="icon" src="/images/web/index/phone.png"></a>',
		'			<a href="#"><img class="icon" src="/images/web/index/weixin.png"></a>',
		'			<a href="#"><img class="icon" src="/images/web/index/weibo.png"></a>',
		'			<a href="#"><img class="icon" src="/images/web/index/qq.png"></a>',
		'		</div>',
		'	</div>',
		'	<div class="middle">',
		'		<img class="logo" src="/images/web/index/logo.png">',
		'		<div class="right">',
		'			<a href="#"><img class="search" src="/images/web/index/search.png"></a>',
		'			<a href="#"><span class="login">登录</span></a>',
		'			<a href="#"><span class="register">注册</span></a>',
		'		</div>',
		'	</div>',
		'	<div class="nav-bar">',
		'		<dl>',
		'			<dt><a href="#">首页</a></dt>',
		'			<dt><a href="#">考研APP</a></dt>',
		'			<dt><a href="#">论坛</a></dt>',
		'			<dt><a href="#">公共课</a></dt>',
		'			<dt class="popup">',
		'				<a href="#" class="title">专业课辅导</a>',
		'				<div class="icon icon-arrow"></div>',
		'				<div class="popup-wrapper">',
		'					<div class="content">',
		'						<p><a href="#">正在建设中...</a></p>',
		'						<p><a href="#">正在建设中...</a></p>',
		'						<p><a href="#">正在建设中...</a></p>',
		'					</div>',
		'				</div>',
		'			</dt>',
		'			<dt><a href="#">集训营</a></dt>',
		'			<dt><a href="#">一对一</a></dt>',
		'			<dt><a href="#">资料下载</a></dt>',
		'		</dl>',
		'	</div>',
		'</div>',
	].join('');

    $('body').prepend($(header));
});
